### ISSUE TITLE
chartVersion is not respected and latest chart is being used always

### ISSUE THREAD

**Issue by arunvelsriram** [gojekfarm/stevedore#44]
Latest bitnami/redis chart version is 12.10.0

Am trying to install 12.8.3 using `chartVersion: 12.8.3` as show in the below manifest:

```yaml
kind: StevedoreManifest
version: 2
deployTo:
  - contextName: minikube
    environmentType: dev
spec:
  - release:
      name: redis
      namespace: default
      chart: bitnami/redis
      chartVersion: 12.8.3
      values:
        password: secret
```

In plan output am getting:

```patch
...
+   labels:
+     app: redis
+     chart: redis-12.10.0
+     release: redis
+     heritage: Helm
...
```

So obviously its using the latest chart always.
